config/routes.rb
FakeTwitter::Application.routes.draw do

  root :to => "home#news_feed"

  get "sign_out" => "session#destroy", :as => "sign_out"
  post "new_tweet" => "tweet#create_tweet"
  get "search" => "search#index"

  resources :user
  resources :session
  resources :tweet

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user

	validates :tweet_data, :length => {:minimum => 1, :maximum => 140}

	scoped_search :on => [:tweet_data]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets

	def full_name 
		fname+ " " +lname
	end 

	def location
		city+ ", " +state
	end 

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
	validates_uniqueness_of :username

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end 
	end

	def self.authenticate(username, password)
		user = User.find_by_username(username)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else 
			nil 
		end
	end 

	mount_uploader :image, ImageUploader

	scoped_search :on => [:fname, :lname, :username]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user 
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'application'

require 'rubygems'
require 'haml'

def news_feed
	@tweet = Tweet.all 
end 



end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	layout "application"

	def index 
		@tweets = Tweet.search_for(params[:search_query])
		@users = User.search_for(params[:search_query])
	end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	layout "application"

	def new 

	end 

	def create
		user = User.authenticate(params[:username].downcase, params[:password])
		if user
			session[:user_id] = user.id
			redirect_to root_path
			flash[:notice] = "You are signed in"
		else 
			flash[:notice] = "Sign In Failed, please try again"
			redirect_to new_session_path
		end
	end 

	def destroy 
		session[:user_id] = nil
		redirect_to root_path
		flash[:notice] = "You have been successfully signed out"
	end 
end 

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
	layout "application"

	def create_tweet
		@tweet = Tweet.create(tweet_params)
		@user = User.find(current_user.id.to_s)
		@user.tweets << @tweet
		if @tweet.save
			flash[:notice] = "Your tweet was created successfully"
		else
			flash[:notice] = "There was a problem creating your tweet"
		end
		redirect_to "/user/#{current_user.id.to_s}"
	end

	private

	def tweet_params
		params.require(:tweet).permit :tweet_data
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	layout "application"

	def new

	end 

	def create
		user = User.create(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to root_path
			flash[:notice] = "Your account has been successfully created and you are now signed in"
		else 
			flash[:notice] = "There was a problem creating your account"
			redirect_to new_user_path
		end 
	end 

	def edit 

	end 

	def update 

	end 

	def show
		@user = User.find(params[:id])
		@tweets = Tweet.where(:user_id => params[:id])
	end 

	def index
		@users = User.all
	end 

	private

	def user_params 
		params.require(:user).permit :fname, :lname, :username, :email, :password, :bio, :url, :city, :state, :image
	end 

end 

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/home/news_feed.haml
%h2 What's going on in the world
-@tweet.each do |tweet|
	-if !tweet.tweet_data.nil?
		%font{:size => "4em"}=tweet.tweet_data
		%br
		%a{:href => "/user/#{tweet.user.id.to_s}"}=tweet.user.username
		%br
		%font{:size => "1.5em"}=tweet.created_at.strftime("%e %b %Y %H:%m:%S%p")
		%br
		%br
	-else

app/views/layouts/application.haml
!!!
%html
	%head
		%title Fake Twitter V2
		=stylesheet_link_tag "bootstrap.min"
		=stylesheet_link_tag "bootstrap-responsive.min"
		=csrf_meta_tags
	%body 
		.row
			.span8.offset2
				%h1 Welcome to Fake Twitter
				-if !flash[:notice].nil?
					.alert=flash[:notice]
				%ul.nav.nav-pills 
					%li 
						=link_to "Home", root_path
					%li 
						=link_to "Users", user_index_path		
					-if current_user.nil? 
						%li 
							=link_to "Sign Up", new_user_path
						%li 
							=link_to "Sign In", new_session_path
					-elsif	 	 
						%li 
							=link_to "Profile", "/user/#{current_user.id.to_s}"
						%li 
							=link_to "Sign Out", sign_out_path
					%form{:class => "navbar-search pull-right", :method => "get", :action => search_path}
						%input{:type => "text", :class => "search_query", :placeholder => "Search Tweets", :name => "search_query"}
			.span10.offset2
				=yield 			

app/views/search/index.haml
%h2 Tweet Results
-@tweets.each do |t|
	=t.tweet_data
	%br
	%a{:href => "/user/#{t.user.id.to_s}"}=t.user.username
	%br

%h2 User Results
-@users.each do |u|
	%a{:href => "/user/#{u.id.to_s}"}=u.username

app/views/session/new.haml
=form_tag "/session" do
  %p
    =label_tag :username
    %br
    =text_field_tag :username, params[:username]
  %p
    =label_tag :password
    %br
    =password_field_tag :password
  %input{:type => "submit", :class => "btn"}

app/views/user/_form.haml
=f.label :First_Name 
=f.text_field :fname
=f.label :Last_Name
=f.text_field :lname
=f.label :Email
=f.text_field :email
=f.label :Username
=f.text_field :username
=f.label :Password
=f.password_field :password
=f.label :Confirm_Password
=f.password_field :confirm_password
=f.label :Bio
=f.text_area :bio
=f.label :Url
=f.text_field :url
=f.label :City
=f.text_field :city
=f.label :State
=f.text_field :state
%br
=f.file_field :image
%br
=f.submit :Submit

app/views/user/index.haml
%h1 Hello There!
-@users.each do |user|
	%a{:href => "user/#{user.id}"}=user.username
	%br 

app/views/user/new.haml
%h1 Sign Up For Fake Twitter
=form_for User.new, :url => "/user" do |f|
	=render "form", {f: f}

app/views/user/show.haml
%h1=@user.full_name
%h3 Profile Picture
=image_tag @user.image_url(:thumb)
%h4 Bio
=@user.bio
%br
%h4 URL
=link_to "#{@user.url}", "http://#{@user.url}", :target => "new"
%h4 Location
=@user.location
%h4 Tweets
-@tweets.each do |t|
	-if !t.tweet_data.nil?
		%font{:size => "4em"}=t.tweet_data 
		%br
		%font{:size => "1.5em"}=t.created_at.strftime("%e %b %Y %H:%m:%S%p")
		%br
	-else

-if current_user == nil

-elsif current_user.id == @user.id
	%h4 Compose your tweet
	=form_for Tweet.new, :url => new_tweet_path do |f|
		=f.text_area :tweet_data
		%br
		=f.submit :Submit